name: Demo CI

on:   
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
  # Run manually.
  workflow_dispatch:

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        run: |
          version=manual-${GITHUB_RUN_ID}
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            version=pr-${GITHUB_RUN_ID}
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            version=$(<VERSION)
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV
          echo "REGISTRY=ghcr.io/${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Build image
        run: |
          make build

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          make push
