name: Demo CI

on:   
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  # Run CI for any PRs.
  pull_request:

  # Run manually.
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        run: |
          version=manual-${GITHUB_RUN_ID}
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            version=pr-${GITHUB_RUN_ID}
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            version=$(<VERSION)
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV
          echo "REGISTRY=ghcr.io/${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Build image
        run: |
          make build

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          make push

  trigger-deployment:
    needs: build-image
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/guestbook-go-config
          token: ${{ secrets.CONFIG_GITHUB_TOKEN }}

      - name: Setup argocd-util
        run: |
          curl -L -o argocd-util "https://github.com/argoproj/argo-cd/releases/download/v2.0.5/argocd-util-linux-amd64"
          chmod +x argocd-util

      - name: Create new env for PR
        run: |
          ./argocd-util app generate-spec guestbook-pr-${GITHUB_RUN_ID} \
            --repo https://github.com/${{ github.repository_owner }}/guestbook-go-config \
            --path overlays/pr \
            --dest-namespace guestbook-pr-${GITHUB_RUN_ID} \
            --dest-server https://kubernetes.default.svc \
            --sync-policy automated \
            --sync-option Prune=true \
            --sync-option SelfHeal=true \
            --sync-option CreateNamespace=true \
            --kustomize-image ghcr.io/${{ github.repository_owner }}/guestbook-go:pr-${GITHUB_RUN_ID} \
          > apps/guestbook-pr-${GITHUB_RUN_ID}.yaml

          git config user.email "guestbook-go-ci@example.com"
          git config user.name "guestbook-go CI"

          git add apps/guestbook-pr-${GITHUB_RUN_ID}.yaml
          git commit -m "Add new app for pr ${GITHUB_RUN_ID}"
          git push origin main