name: Demo CI

on:   
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - seed

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
  # Run manually.
  workflow_dispatch:

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=pr-${GITHUB_RUN_ID} REGISTRY=ghcr.io/${{ github.repository_owner }} make build

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          VERSION=pr-${GITHUB_RUN_ID} REGISTRY=ghcr.io/${{ github.repository_owner }} make push